# Generated by Django 5.0.6 on 2024-06-15 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Apprenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('note_softskills', models.IntegerField()),
                ('referentiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprentis.referentiel')),
            ],
        ),
    ]
